
package com.mediatek.encapsulation.com.mediatek.common.mms;

import com.mediatek.common.sms.IConcatenatedSmsFwkExt;
import com.mediatek.encapsulation.EncapsulationConstant;


/** This Class is generated by mediatek */

public interface EncapsulatedIConcatenatedSmsFwkExt {

    public static final String UPLOAD_FLAG_TAG = EncapsulationConstant.USE_MTK_PLATFORM ?
                    IConcatenatedSmsFwkExt.UPLOAD_FLAG_TAG : "upload_flag";

    public static final int UPLOAD_FLAG_NEW = EncapsulationConstant.USE_MTK_PLATFORM ?
                    IConcatenatedSmsFwkExt.UPLOAD_FLAG_NEW : 1;

    public static final int UPLOAD_FLAG_UPDATE = EncapsulationConstant.USE_MTK_PLATFORM ?
                    IConcatenatedSmsFwkExt.UPLOAD_FLAG_UPDATE : 2;
}
