
package com.mediatek.encapsulation.com.mediatek.common.featureoption;

import com.mediatek.common.featureoption.FeatureOption;
import com.mediatek.encapsulation.EncapsulationConstant;


/** This Class is generated by mediatek */

public final class EncapsulatedExtFeatureOption {
    public static final boolean EVDO_DT_SUPPORT = EncapsulationConstant.USE_MTK_PLATFORM ? FeatureOption.EVDO_DT_SUPPORT :
                                                        true;
}
